In [31]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print('a + b:', a + b)
print('a - b:', a - b)
print('a ^ 2:', a ** 2)
print('a < 2:', a < 2)
print('sin(a):', np.sin(a))

a + b: [5 7 9]
a - b: [-3 -3 -3]
a ^ 2: [1 4 9]
a < 2: [ True False False]
sin(a): [0.84147098 0.90929743 0.14112001]


In [32]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

In [33]:
print(a*b) # element wise prodcut

[[ 1  4  9]
 [16 25 36]]


In [34]:
# matrix prodcut (satır ve sütün uyumlu olmalı. a=2,3 ise b=3,2 olmalı
a.dot(b.T)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
print(np.exp(a))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [37]:
array1 = np.random.random((5,5)) # 5x5 lik 0-1 arasında rasgele elemanları olan matris oluşturur.
print('Matrix:', array1)
print('\nSum of elements:', array1.sum()) # arrayin içindeki elemanların toplamı
print('Maximum value of elements:', array1.max()) # arrayin içindeki elemanların toplamı
print('Minimum value of elements:', array1.min()) # arrayin içindeki elemanların toplamı
print('Sum of columns:', a.sum(axis=0))
print('Sum of rows:', a.sum(axis=1))
print('Square root of elements:\n', np.sqrt(a))
print('Square of elements:\n', np.square(a)) # a ** 2
print('Sum of a+a:\n', np.add(a,a)) # or a+a

Matrix: [[0.69429069 0.71843031 0.32859167 0.9788349  0.20446989]
 [0.95578369 0.15953539 0.09688165 0.04659447 0.93355531]
 [0.01361405 0.88941639 0.86569493 0.81310053 0.10521195]
 [0.82199072 0.16146101 0.32070385 0.79373829 0.09564678]
 [0.34205724 0.74914709 0.18230117 0.41854374 0.60455897]]

Sum of elements: 12.294154678370019
Maximum value of elements: 0.9788348961481641
Minimum value of elements: 0.013614053745868548
Sum of columns: [5 7 9]
Sum of rows: [ 6 15]
Square root of elements:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Square of elements:
 [[ 1  4  9]
 [16 25 36]]
Sum of a+a:
 [[ 2  4  6]
 [ 8 10 12]]
