In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print('a + b:', a + b)
print('a - b:', a - b)
print('a ^ 2:', a ** 2)
print('a < 2:', a < 2)
print('sin(a):', np.sin(a))

a + b: [5 7 9]
a - b: [-3 -3 -3]
a ^ 2: [1 4 9]
a < 2: [ True False False]
sin(a): [0.84147098 0.90929743 0.14112001]


In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

In [3]:
print(a*b) # element wise prodcut

[[ 1  4  9]
 [16 25 36]]


In [4]:
# matrix prodcut (satır ve sütün uyumlu olmalı. a=2,3 ise b=3,2 olmalı
a.dot(b.T)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(np.exp(a))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [6]:
array1 = np.random.random((5,5)) # 5x5 lik 0-1 arasında rasgele elemanları olan matris oluşturur.
print('Matrix:', array1)
print('\nSum of elements:', array1.sum()) # arrayin içindeki elemanların toplamı
print('Maximum value of elements:', array1.max()) # arrayin içindeki elemanların toplamı
print('Minimum value of elements:', array1.min()) # arrayin içindeki elemanların toplamı
print('Sum of columns:', a.sum(axis=0))
print('Sum of rows:', a.sum(axis=1))
print('Square root of elements:\n', np.sqrt(a))
print('Square of elements:\n', np.square(a)) # a ** 2
print('Sum of a+a:\n', np.add(a,a)) # or a+a

Matrix: [[0.43279719 0.97938857 0.20952242 0.72871017 0.79552074]
 [0.20660956 0.21334531 0.37475473 0.87095734 0.81187333]
 [0.47425116 0.24304781 0.85327812 0.29917852 0.70366373]
 [0.19459752 0.8418647  0.28306284 0.3249931  0.58243898]
 [0.80530443 0.57772997 0.89745502 0.13835033 0.67879401]]

Sum of elements: 13.521489590596664
Maximum value of elements: 0.97938857334388
Minimum value of elements: 0.13835033163585708
Sum of columns: [5 7 9]
Sum of rows: [ 6 15]
Square root of elements:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Square of elements:
 [[ 1  4  9]
 [16 25 36]]
Sum of a+a:
 [[ 2  4  6]
 [ 8 10 12]]
