In [1]:
import numpy as np
array1 = np.array([1,2,3,4,5,6,7])   #  vector dimension = 1 (arrayler list yapısına çok benzer pythonda da)

In [2]:
print(array1[0])
print(array1[0:4]) # 0.intexten 4. indexe kadar(4 exclusive)

1
[1 2 3 4]


In [3]:
reverse_array = array1[::-1]

In [4]:
array2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array2)
print()
print('array2[1][1] :', array2[1][1])
print('array2[:,1]  :', array2[:,1]) # : ile satırların hepsini ve 1. sütunu al
print('array2[:,1]  :',array2[:,1]) # : 1. satırı al ve tüm sütunları al.
print('array2[1,1:4]:',array2[1,1:4]) # 1. satırı al ve 1,2 ve 3. sütunları al.
print('array2[-1,:] :',array2[-1,:]) # en son satırı ve tüm sütunları al.
print('array2[:,-1] :',array2[:,-1]) # en son sütunu ve tüm satırları al.

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

array2[1][1] : 7
array2[:,1]  : [2 7]
array2[:,1]  : [2 7]
array2[1,1:4]: [7 8 9]
array2[-1,:] : [ 6  7  8  9 10]
array2[:,-1] : [ 5 10]
