In [5]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3x3 array
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### IMPORTONT: We will use to flatten method in CNN!

In [6]:
array2 = array1.ravel() # array 1x9 (arrayi düz hale getirmek)
print(array2)

[1 2 3 4 5 6 7 8 9]


In [9]:
array3 = array2.reshape(3,3) # Tekrardan 3x3 lük yapmak icin
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
array3T = array3.T
print(array3T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
print(array3T.shape) # shape=bicim, form 3x3

(3, 3)


In [13]:
array4 = np.array([[1,2],[3,4],[4,5]])
print(array4)

[[1 2]
 [3 4]
 [4 5]]


In [16]:
array4.reshape(2,3) # 3,2 lik matrisi => 2,3 lük yapar. Ancak array aşağıda görüldüğü gibi gerçekten de değişmez.

array([[1, 2, 3],
       [4, 4, 5]])

In [17]:
print(array4)

[[1 2]
 [3 4]
 [4 5]]


> Array'i **reshape** ile geçici olarak satır ve sütununu güncelleriz. reshape'i bir değişkeni eşitlersek kalıcı olarak güncelleyebiliriz. 
>
>Bunu yapmak yerine satır ve sütunlarını kalıcı olarak güncellemek için **resize** kullanırız.

In [20]:
array4.resize((2,3))
print(array4)

[[1 2 3]
 [4 4 5]]
