In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])  # 1*15 vector
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
print(array1.shape) # 15x1 =15,

(15,)


In [4]:
a = array1.reshape(3,5) # arrayi istediğimiz matris boyutuna güncellemek için reshape kullanılır.
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
print("shape:", a.shape) # matris boyutunu gormek için,
print("dimension:", a.ndim)  # 2D boyutlu array oldugunu gormek icin

shape: (3, 5)
dimension: 2


In [6]:
print("data type: ",a.dtype.name) # arrayin icindeki veri tiplerinin ismi
print("size: ",a.size) # reshapeden onceki boyutunu verecek
print("type: ",type(a)) # a arrayinin tipi = array


data type:  int32
size:  15
type:  <class 'numpy.ndarray'>


In [7]:
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,5]]) # reshape kullanmaksızın manual olarak matris oluşturulabilir.
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 5]])

In [8]:
array2.shape # matris boyutu

(3, 4)

In [9]:
zeros = np.zeros((3,4)) # 3x4 lük 0'lardan olusan matris olusturmak icin allocate edilir.
zeros
# list1.append(4) # append methodu memory'ye yük bindirir, program yavaşlar. O yüzden 0'lardan oluşan bir array allocate ederiz, güncellemek istediğimiz field'ı güncellememizi yaparız.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
zeros[0, 0] = 5
zeros

array([[5., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
ones = np.ones((3,4)) # 1'lerden oluşan matris oluşturmak için
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
empty_array = np.empty((1,3)) # empty bir array oluşturur. aşağıdaki e-311 vs empty olduğunu gösterir.
empty_array

array([[8.65894266e-312, 0.00000000e+000, 4.94065646e-324]])

In [13]:
b = np.arange(1,20) # 1'den 20'ye kadar array oluşturur.(20 exclusive)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [14]:
c = np. arange(1, 20, 5) # 1'den 20'ye kadar 5'erli bir array oluşturur. (20 exclusive)
c

array([ 1,  6, 11, 16])

In [15]:
d = np.linspace(1,10,5) # 1'den 10'a kadar (10 inclusive) eşit aralıkları olan 5 elaman oluşturur.
print(d)

[ 1.    3.25  5.5   7.75 10.  ]
