In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print('a + b:', a + b)
print('a - b:', a - b)
print('a ^ 2:', a ** 2)
print('a < 2:', a < 2)
print('sin(a):', np.sin(a))

a + b: [5 7 9]
a - b: [-3 -3 -3]
a ^ 2: [1 4 9]
a < 2: [ True False False]
sin(a): [0.84147098 0.90929743 0.14112001]


In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

In [3]:
print(a*b) # element wise prodcut

[[ 1  4  9]
 [16 25 36]]


In [4]:
# matrix prodcut (satır ve sütün uyumlu olmalı. a=2,3 ise b=3,2 olmalı
a.dot(b.T)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(np.exp(a))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [6]:
array1 = np.random.random((5,5)) # 5x5 lik 0-1 arasında rasgele elemanları olan matris oluşturur.
print('Matrix:', array1)
print('\nSum of elements:', array1.sum()) # arrayin içindeki elemanların toplamı
print('Maximum value of elements:', array1.max()) # arrayin içindeki elemanların toplamı
print('Minimum value of elements:', array1.min()) # arrayin içindeki elemanların toplamı
print('Sum of columns:', a.sum(axis=0))
print('Sum of rows:', a.sum(axis=1))
print('Square root of elements:\n', np.sqrt(a))
print('Square of elements:\n', np.square(a)) # a ** 2
print('Sum of a+a:\n', np.add(a,a)) # or a+a

Matrix: [[0.33997935 0.94255535 0.3721431  0.94751957 0.50454908]
 [0.99223389 0.13478773 0.16776122 0.15497322 0.53092283]
 [0.57487383 0.26390591 0.61863428 0.76787484 0.89896636]
 [0.04846562 0.20356757 0.58589615 0.34666501 0.93725573]
 [0.32338884 0.05046775 0.51572915 0.77045534 0.97305838]]

Sum of elements: 12.966630119594845
Maximum value of elements: 0.9922338934654449
Minimum value of elements: 0.048465615849364485
Sum of columns: [5 7 9]
Sum of rows: [ 6 15]
Square root of elements:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Square of elements:
 [[ 1  4  9]
 [16 25 36]]
Sum of a+a:
 [[ 2  4  6]
 [ 8 10 12]]


### Generate Random Array

In [15]:
random_array1 = np.random.randint(10, size = (5)) # Five numbers from 0 to 10 are added to the array. 
print(random_array1)

[3 2 5 8 1]


In [16]:
random_array2 = np.random.randint(10, size = (5,5)) # Numbers from 0 to 10 are added to the 5x5 array. 
print(random_array2)

[[6 7 5 0 3]
 [2 4 7 9 5]
 [1 8 1 3 7]
 [5 1 8 5 3]
 [7 7 4 4 9]]
