In [1]:
import numpy as np
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[-1,-2],[-3,-4]])
print(array1)
print()
print(array2)

[[1 2]
 [3 4]]

[[-1 -2]
 [-3 -4]]


In [2]:
array3 = np.vstack((array1,array2)) # vertical stack (merge)
print(array3)

[[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]]


In [3]:
array4 = np.hstack((array1,array2)) # vertical stack (merge)
print(array3)

[[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]]
