In [1]:
import cv2
import numpy as np

In [2]:
# import image
img = cv2.imread("kart.png")
cv2.imshow("Originalf", img)

In [3]:
width = 400
height = 500

In [4]:
points1 = np.float32([[230,1],[1,472],[540,150],[338,617]])
points2 = np.float32([[0,0],[0, height],[width,0],[width,height]])  #istenilen resim konumu

In [5]:
matrix = cv2.getPerspectiveTransform(points1, points2)
print(matrix)

[[ 9.88318421e-01  4.80519997e-01 -2.27793757e+02]
 [-4.28952606e-01  8.92451730e-01  9.77666476e+01]
 [-1.23898125e-04  7.89697479e-05  1.00000000e+00]]


In [6]:
# nihai dönüştürülmüş resim
imgOutput = cv2.warpPerspective(img, matrix, (width,height))
cv2.imshow("Nihai Resim", imgOutput)

In [7]:
if cv2.waitKey(0) == ord("q"): cv2.destroyAllWindows() # q'ya basılınca çıkış yapsın