## What is Pytorch?
- It’s a Python based scientific computing package targeted at two sets of audiences:
    - A replacement for NumPy to use the **power of GPUs**
    - Deep learning research platform that provides maximum **flexibility** and **speed**
- pros: 
    - Interactively debugging PyTorch. Many users who have used both frameworks would argue that makes pytorch significantly easier to **debug** and visualize.
    - Clean support for dynamic graphs
    - Organizational backing from Facebook
    - Blend of high level and low level APIs
- cons:
    - Much less mature than alternatives
    - Limited references / resources outside of the official documentation
<br>
<br>**Content:**
1. [Basics of Pytorch](#1)
    - Matrices
    - Math
    - Variable
2. [Linear Regression](#2)
3. [Logistic Regression](#3)
4. [Artificial Neural Network (ANN)](#4)
5. [Concolutional Neural Network (CNN)](#5)
6. Recurrent Neural Network (RNN)
    - https://www.kaggle.com/kanncaa1/recurrent-neural-network-with-pytorch
7. Long-Short Term Memory (LSTM)
    - https://www.kaggle.com/kanncaa1/long-short-term-memory-with-pytorch

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import torch
from torch.autograd import Variable # import variable from pytorch library

# 1-Basics of Pytorch
## A. Matrices
- In pytorch, matrix(array) is called tensors.
- 3*3 matrix koy. This is 3x3 tensor.
- Lets look at array example with numpy that we already know.
    - We create numpy array with np.numpy() method
    - Type(): type of the array. In this example it is numpy
    - np.shape(): shape of the array. Row x Column

<img src="img/tensor.png" style="height:400px">

    i) List to Torch

In [2]:
list1 = [[1,2,3],[4,5,6]]
type(list1)

list

In [3]:
# numpy array
first_array = np.array(list1) # 2x3 array
print("Array Type: {}".format(type(first_array))) # type
print("Array Shape: {}".format(np.shape(first_array))) # shape
print(first_array)

Array Type: <class 'numpy.ndarray'>
Array Shape: (2, 3)
[[1 2 3]
 [4 5 6]]


- We looked at numpy array.
- Now examine how we implement tensor(pytorch array)
- import pytorch library with import torch
- We create tensor with torch.Tensor() method
- type: type of the array. In this example it is tensor
- shape: shape of the array. Row x Column

In [4]:
# pytorch array
tensor1 = torch.Tensor(list1)
print("Array Type: {}".format(type(tensor1))) # type
print("Array Shape: {}".format(tensor1.shape)) # shape
print(tensor1)

Array Type: <class 'torch.Tensor'>
Array Shape: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


    ii. Allocate in Pytorch

- Allocation is one of the most used technique in coding. Therefore lets learn how to make it with pytorch.
- In order to learn, compare numpy and tensor
    - **np.ones()** = **torch.ones()**
    - **np.random.rand()** = **torch.rand()**

In [5]:
# numpy ones
print("Numpy: {}\n".format(np.ones((2,3))))

# pytorch ones
print(torch.ones((2,3)))

Numpy: [[1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# numpy random
print("Numpy {}\n".format(np.random.rand(2,3)))

# pytorch random
print(torch.rand(2,3))

Numpy [[0.87533619 0.76582744 0.05101395]
 [0.03696042 0.45249243 0.4098491 ]]

tensor([[0.2560, 0.4036, 0.5710],
        [0.2659, 0.5305, 0.6580]])


    iii. Convert from Numpy to Tensor

- Even if when I use pytorch for neural networks, I feel better if I use numpy. Therefore, usually convert result of neural network that is tensor to numpy array to visualize or examine.
- Lets look at conversion between tensor and numpy arrays.
    - torch.from_numpy(): from numpy to tensor
    - numpy(): from tensor to numpy

In [7]:
# random numpy array
array = np.random.rand(2,2)
print("{} {}\n".format(type(array),array))

# from numpy to tensor
from_numpy_to_tensor = torch.from_numpy(array)
print("{}\n".format(from_numpy_to_tensor))

# from tensor to numpy
tensor = from_numpy_to_tensor
from_tensor_to_numpy = tensor.numpy()
print("{} {}\n".format(type(from_tensor_to_numpy),from_tensor_to_numpy))

<class 'numpy.ndarray'> [[0.55649326 0.34807357]
 [0.83817526 0.43898714]]

tensor([[0.5565, 0.3481],
        [0.8382, 0.4390]], dtype=torch.float64)

<class 'numpy.ndarray'> [[0.55649326 0.34807357]
 [0.83817526 0.43898714]]



## B) Basic Math with Pytorch
- Resize: **view()**
- a and b are tensor.
- Addition: torch.add(a,b) = a + b
- Subtraction: a.sub(b) = a - b
- Element wise multiplication: torch.mul(a,b) = a * b 
- Element wise division: torch.div(a,b) = a / b 
- Mean: a.mean()
- Standart Deviation (std): a.std()

In [8]:
tensor1 = torch.ones(3,3)
print(tensor1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [9]:
# Resize
tensor1.view(9).shape, tensor1.view(9) # vector

(torch.Size([9]), tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [10]:
tensor2 = torch.add(tensor1, tensor1) # Addition
tensor2

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [11]:
tensor2.sub(tensor1) # Subtraction => tensor2-tensor1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.mul(tensor1, tensor2) # Element wise multiplication => tensor1xtensor2

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [13]:
torch.div(tensor1, tensor2) # # Element wise division # tensor1 / tensor2 = 1/2

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

In [14]:
tensor3 = torch.Tensor([1,2,3,4,5])
print("Mean: {}".format(tensor3.mean())) # Mean

print("std: {}".format(tensor3.std())) # Standart deviation (std)

Mean: 3.0
std: 1.5811388492584229


## C) Variables
- It accumulates gradients. 
- We will use pytorch in neural network. And as you know, in neural network we have backpropagation where gradients are calculated. Therefore we need to handle gradients. If you do not know neural network, check my deep learning tutorial first because I will not explain detailed the concepts like optimization, loss function or backpropagation. 
- Deep learning tutorial: https://www.kaggle.com/kanncaa1/deep-learning-tutorial-for-beginners
- Difference between variables and tensor is variable accumulates gradients.
- We can make math operations with variables, too.
- In order to make backward propagation we need variables

In [15]:
#define variable
var1 = Variable(torch.ones(3), requires_grad = True) # requires_grad= gradient bulma işlemi olacak.
var1 # gradientleri depolar.

tensor([1., 1., 1.], requires_grad=True)

- Assume we have equation y = x^2
- Define x = [2,4] variable
- After calculation we find that y = [4,16] (y = x^2)
- Recap o equation is that o = (1/2)*sum(y) = (1/2)*sum(x^2)
- deriavative of o = x
- Result is equal to x so gradients are [2,4]
- Lets implement

<img src="img/variable.png" style="height:300px">

In [16]:
# lets make basic backward propagation
# we have an equation that is y = x^2
array1 = [2,4]
tensor1 = torch.Tensor(array1)
print("this is tensor:", tensor1)

x = Variable(tensor1, requires_grad = True)
print("\nthis is x variable:", tensor1)

this is tensor: tensor([2., 4.])

this is x variable: tensor([2., 4.])


In [17]:
y = x**2  # y=x^2
print("y =", y)

y = tensor([ 4., 16.], grad_fn=<PowBackward0>)


In [18]:
# recap o equation o = 1/2*sum(y)
o = (1/2) * sum(y) # 1/2*(4+16)
print("o = ", o)

o =  tensor(10., grad_fn=<MulBackward0>)


In [19]:
# backward => x'e kadar backward yapar. Çünkü o y'den türer, y'de x'den türer.
o.backward() # calculates gradients 

# As I defined, variables accumulates gradients. In this part there is only one variable x.
# Therefore variable x should be have gradients
# Lets look at gradients with x.grad
print("gradients: ", x.grad) # x'i verir.

gradients:  tensor([2., 4.])
