<img src="images/yolo.png" style="height: 400px">

In [1]:
import cv2
import numpy as np
from yolo_model import YOLO

In [2]:
yolo = YOLO(0.6, 0.5) # These values are used in the literature.
file = "data/coco_classes.txt"

## 1-Read Dataset

In [3]:
with open(file) as f:
    class_name = f.readlines()
class_name[0:5]

['person\n', 'bicycle\n', 'car\n', 'motorbike\n', 'aeroplane\n']

In [4]:
all_classes = [c.strip() for c in class_name]
all_classes[0:5]

['person', 'bicycle', 'car', 'motorbike', 'aeroplane']

In [5]:
f = "dog_cat.jpg"
path = "images/"+f
image = cv2.imread(path)
cv2.imshow("image",image)

if cv2.waitKey(0) == ord("q"): 
    cv2.destroyAllWindows()

## 2-Preprocessing

In [6]:
pimage = cv2.resize(image, (416, 416))
pimage = np.array(pimage, dtype = "float32")
pimage /= 255.0
pimage = np.expand_dims(pimage, axis = 0) # listenin içine extra satır ekledi.=> yolo için gerekli.

## 3-Predict Data

In [7]:
boxes, classes, scores = yolo.predict(pimage, image.shape)

In [8]:
boxes

array([[260.29616654,  41.1714192 , 540.11216569, 880.82198489],
       [782.28799295, 140.79580593, 582.33294046, 781.46666098]])

In [9]:
classes # cat, dog

array([16, 15], dtype=int64)

In [10]:
scores

array([0.99748564, 0.99598086], dtype=float32)

## 4-Testing Data

In [11]:
for box, score, cl in zip(boxes, scores, classes):
    
    x,y,w,h = box
    
    # 0.5 kadaar hafif bir pay bıraktığımız için, rectangle daha güzel görülecek.
    top = max(0, np.floor(x + 0.5).astype(int)) # floor(1.9) = 1
    left = max(0, np.floor(y + 0.5).astype(int)) 
    right = max(0, np.floor(x + w + 0.5).astype(int))
    bottom = max(0, np.floor(y + h + 0.5).astype(int))

    cv2.rectangle(image, (top,left), (right, bottom),(255,0,0),2)
    cv2.putText(image, "{} {}".format(all_classes[cl],score),(top,left-6),cv2.FONT_HERSHEY_SIMPLEX,0.6,(0,0,255),1,cv2.LINE_AA)

In [12]:
cv2.imshow("yolo", image)
if cv2.waitKey(0) == ord("q"): 
    cv2.destroyAllWindows()